# Homework 1

#### Jacqueline Duong

#### Phys 243

## -------------------------------------------

# Problem 1: Python Programming

### Part 1: Rewrite the function with for loop

In [4]:
def Fib_rec(n):
    fib_seq = [0, 1]
    #first 2 values of Fibonacci sequence
    for i in range(2, n+1):
        #set the range function
        fib_seq.append(fib_seq[i-1] + fib_seq[i-2])
        #append the remaining values
    return fib_seq[n]
print(Fib_rec(n))

### Part 2: Which function is faster

#### The function with for loop is faster because it uses iteration instead of repeated function calls, which makes it faster and more efficient. A for loop is especially useful for the Fibonacci sequence, which has an iterative pattern. 

### Part 3: Write a code to find the average time for k times function call

In [5]:
import time

x = time.time

def timer(n, k, f=Fib_rec):
    run_time = 0

    for _ in range(k):
    #for loop for k iterations
        start_time = time.time()
        #measures start time for function runs
        f(n)
        #call function to time
        end_time = time.time()
        ##measures time after the function has run

        run_time += end_time - start_time
        #takes the diffence to find the time it took for the function to run

    average_time = run_time / k
    return average_time

### Part 4: Make a plot

In [ ]:
import time
import matplotlib.pyplot as plt

def Fib_rec(n):
    if n == 0:
        return 1
    elif n == 1:
        return 1
    else:
        return Fib_rec(n - 1) + Fib_rec(n - 2)
#recursive function

def Fib_iter(n):
    fib_seq = [0, 1]
    for i in range(2, n + 1):
        fib_seq.append(fib_seq[i - 1] + fib_seq[i - 2])
    return fib_seq[n]
#non-recursive function

def timer(n, k, f=Fib_rec):
    run_time = 0

    for _ in range(k):
        start_time = time.time()
        f(n)
        end_time = time.time()

        run_time += end_time - start_time

    average_time = run_time / k
    return average_time
#average time

# Input values for the x-axis
input_values = [10, 20, 30, 40, 50]

# Number of runs for each input
k = 10

# Calculate average times for both functions
recursive_times = []
iterative_times = []

for n in input_values:
    recursive_avg_time = timer(n, k, Fib_rec)
    iterative_avg_time = timer(n, k, Fib_iter)

    recursive_times.append(recursive_avg_time)
    iterative_times.append(iterative_avg_time)

# Create the plot
plt.plot(input_values, recursive_times, label="Recursive")
plt.plot(input_values, iterative_times, label="Non-recursive")

plt.xlabel("n")
plt.ylabel("Average Time (seconds)")
plt.title("Recursive vs. Non-recursive Average Time Comparison")
plt.legend()

plt.show()

# Problem 2: Linear Algebra

### M = [[1, -4, 2], 
### [-4, 1, -2], 
### [2, -2, -2]]

### Part 1: Find determinant, transpose, and inverse for M

In [3]:
import numpy as np
  
# creating a 3x3 Numpy matrix
matrix = np.array([[1, -4, 2], [-4, 1, -2], [2, -2, -2]])
  
# calculating the determinant of matrix
det = np.linalg.det(matrix)
  
print(int(det))
#the determinant is 54

54


In [5]:
import numpy as np
  
matrix = np.array([[1, -4, 2], [-4, 1, -2], [2, -2, -2]])

print(matrix.T)
#prints the transpose

[[ 1 -4  2]
 [-4  1 -2]
 [ 2 -2 -2]]


In [6]:
import numpy as np
  
matrix = np.array([[1, -4, 2], [-4, 1, -2], [2, -2, -2]])

print(np.linalg.inv(matrix))
#prints the inverse

[[-0.11111111 -0.22222222  0.11111111]
 [-0.22222222 -0.11111111 -0.11111111]
 [ 0.11111111 -0.11111111 -0.27777778]]


### Part 2: Find the eigenvalues and eigenvectors for M

In [12]:
import numpy as np
  
matrix = np.array([[1, -4, 2], [-4, 1, -2], [2, -2, -2]])

eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n",eigenvectors) 

Eigenvalues:
 [-3.  6. -3.]
Eigenvectors:
 [[-0.74535599 -0.66666667 -0.13728249]
 [-0.59628479  0.66666667  0.32973659]
 [ 0.2981424  -0.33333333  0.93403817]]


### Part 3: Find the Gradient

### Part 4: Find the Hessian Matrix

In [15]:
from sympy import symbols, diff, sin, Matrix

x, y, z = symbols('x y z')
#variables defined

g = (x**3 * y) + (y * z * sin(x)) + (x * (y**2) * (z**5))
#function defined

hessian = ([[diff(diff(g, var1), var2) for var1 in (x, y, z)] for var2 in (x, y, z)])
#calculate hessian matrix

print(hessian)

[[6*x*y - y*z*sin(x), 3*x**2 + 2*y*z**5 + z*cos(x), 5*y**2*z**4 + y*cos(x)], [3*x**2 + 2*y*z**5 + z*cos(x), 2*x*z**5, 10*x*y*z**4 + sin(x)], [5*y**2*z**4 + y*cos(x), 10*x*y*z**4 + sin(x), 20*x*y**2*z**3]]


# Problem 3: Machine Learning

### Part 1: Validation vs test samples

A validation set is used to validate the model and fine tune it. It tests how accurate the model being used is. The test samples are used once the model reaches it final stage. The test samples include unseen data or images to see how well the model does.

### Part 2: Supervised vs unsupervised learning algorithm

Supervised learning algorithm refers to automatic learning that involves both the input and output relationships. Unsupervised learning algorithm refers to automatic learning of the rules that descibe only the input data, not the output. While supervised learning involves classified/labeled data, unsupervised is concerned with unclassified/unlabeled data. 

### Part 3: Define optimization and describe its relationship with Machine Learning

Optimization is the process of determining the proper parameters. As a result, optimization is an important process in Machine Learning because it is used to search the parameters of a learning model by finding the best fit to the data. An optimum parameter fit is indicated by a low cost function value. 